#  _____           _                               ____                _   _
# | ____|  _ __   (_)   __ _   _ __ ___     __ _  / ___|   _ __ ___   (_) | |   ___   ___
# |  _|   | '_ \  | |  / _` | | '_ ` _ \   / _` | \___ \  | '_ ` _ \  | | | |  / _ \ / __|
# | |___  | | | | | | | (_| | | | | | | | | (_| |  ___) | | | | | | | | | | | |  __/ \__ \
# |_____| |_| |_| |_|  \__, | |_| |_| |_|  \__,_| |____/  |_| |_| |_| |_| |_|  \___| |___/
#                      |___/
#
# Плагин: EnigmaSmiles v1.2
#  Автор: Er1one (vk.com/er1one)
#
messages:
  no-perms: "&6&lEnigmaSmiles &8» &cНе хватает прав"
  reloaded: "&6&lEnigmaSmiles &8» &aПлагин перезагружен! Загружено &a&l%amount%&a эмоджи"

smiles:
  love:
    permission: "smiles.love"
    input: "<3"
    output: "&c❤&r"
  sad:
    permission: "smiles.star"
    input: ":star:"
    output: "&e✯&r"
  cross:
    permission: "smiles.cross"
    input: ":cross:"
    output: "&e✟&r"
  snowflake:
    permission: "smiles.snowflake"
    input: ":snowflake:"
    output: "&9❄&r"
  circle:
    permission: "smiles.circle"
    input: ":circle:"
    output: "&6◯&r"
  sun:
    permission: "smiles.sun"
    input: ":sun:"
    output: "&e☀&r"
  dead:
    permission: "smiles.dead"
    input: ":dead:"
    output: "&0☠&r"