#  _____           _                               ____                _   _
# | ____|  _ __   (_)   __ _   _ __ ___     __ _  / ___|   _ __ ___   (_) | |   ___   ___
# |  _|   | '_ \  | |  / _` | | '_ ` _ \   / _` | \___ \  | '_ ` _ \  | | | |  / _ \ / __|
# | |___  | | | | | | | (_| | | | | | | | | (_| |  ___) | | | | | | | | | | | |  __/ \__ \
# |_____| |_| |_| |_|  \__, | |_| |_| |_|  \__,_| |____/  |_| |_| |_| |_| |_|  \___| |___/
#                      |___/
#
# Плагин: EnigmaSmiles v1.2
#  Автор: Er1one (vk.com/er1one)
#
name: EnigmaSmiles
version: v1.2
main: ru.er1one.enigmasmiles.EnigmaSmiles
authors: [ er1one ]
description: The plugin allows players to insert emoticons in their messages
website: https://vk.com/er1one
commands:
  smiles: